In [30]:
import numpy as np
d = np.arange(21)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [32]:
d[0:21:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
d[0:21:3]

array([ 0,  3,  6,  9, 12, 15, 18])