In [33]:
import numpy as np
array1 = np.array(range(30))
array3 = array1.reshape(5,6)
array4 = (array3 % 6) == 1
print(array4)
print(array3)

[[False  True False False False False]
 [False  True False False False False]
 [False  True False False False False]
 [False  True False False False False]
 [False  True False False False False]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [34]:
array4 =  np.where(array2 == True)
array4

(array([ 1,  7, 13, 19, 25], dtype=int64),)